#
# Data Source Validator - app.conf
#

[install]
is_configured = false
state = enabled
build = 1

[ui]
is_visible = true
label = Data Source Validator
setup_view = setup
docs_section_override = datasourcevalidator

[launcher]
author = [YOUR ORG]
version = 1.0.1
description = Validates that user-defined data sources, grouped under parent platforms, currently return at least one event.

[id]
name = datasource_validator
version = 1.0.1

[package]
id = datasource_validator
check_for_updates = true

[triggers]
reload.datasource_validator_restmap = simple
reload.datasource_validator_collections = simple
reload.datasource_validator_authorize = simple
